# Generated by Django 4.2 on 2023-05-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('CarPlate', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Type', models.TextField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='ClientId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
