# Generated by Django 4.2 on 2023-05-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_car_remove_client_id_alter_client_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Capacity',
            field=models.IntegerField(default=100),
        ),
    ]
