# Generated by Django 4.2 on 2023-05-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_car_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientId', models.CharField(max_length=100)),
                ('CarPlate', models.CharField(max_length=100)),
                ('TotalPaid', models.IntegerField(default=100)),
                ('StartDate', models.DateField(null=True)),
                ('ReturnDate', models.DateField(null=True)),
            ],
        ),
    ]
