# Generated by Django 4.2 on 2023-05-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0005_alter_rental_record_carplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='CarStatus',
            field=models.TextField(default='Ok'),
        ),
    ]
