# Generated by Django 4.2 on 2023-05-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beauty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingNo', models.CharField(max_length=100)),
                ('PackID', models.CharField(max_length=100)),
                ('StartDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackID', models.CharField(max_length=100)),
                ('PackName', models.TextField(max_length=200)),
            ],
        ),
    ]
