# Generated by Django 4.2 on 2023-05-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beauty', '0002_customer_booking_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='PackPrice',
            field=models.IntegerField(default=100),
        ),
    ]
